language: generic
sudo: false

before_install:
  - ./new_comp.sh

install:
  - ./install.sh
script:
  - zsh  -c '[[ -z "$(source "$HOME/.zshrc"  &>/dev/null)" ]]'
  - bash -c '[[ -z "$(source "$HOME/.bashrc" &>/dev/null)" ]]'
os:
  - linux
  - osx
notifications:
  email: false

addons:
  apt:
    packages:
    - nvim
    - git
    - git-extras
    - tmux
    - xbindkeys
    - zsh
    - z
